<?php

namespace ContainerVtRVYEY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminNewsDeleteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminNewsDeleteController' shared autowired service.
     *
     * @return \App\Controller\AdminNewsDeleteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdminNewsDeleteController.php';

        $container->services['App\\Controller\\AdminNewsDeleteController'] = $instance = new \App\Controller\AdminNewsDeleteController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\AdminNewsDeleteController', $container));

        return $instance;
    }
}
