<?php

namespace Container4Kgf7rx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartenersControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PartenersController' shared autowired service.
     *
     * @return \App\Controller\PartenersController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PartenersController.php';

        $container->services['App\\Controller\\PartenersController'] = $instance = new \App\Controller\PartenersController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\PartenersController', $container));

        return $instance;
    }
}
