<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221229115343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE directus_collections DROP FOREIGN KEY directus_collections_group_foreign');
        $this->addSql('ALTER TABLE directus_dashboards DROP FOREIGN KEY directus_dashboards_user_created_foreign');
        $this->addSql('ALTER TABLE directus_files DROP FOREIGN KEY directus_files_modified_by_foreign');
        $this->addSql('ALTER TABLE directus_files DROP FOREIGN KEY directus_files_uploaded_by_foreign');
        $this->addSql('ALTER TABLE directus_files DROP FOREIGN KEY directus_files_folder_foreign');
        $this->addSql('ALTER TABLE directus_flows DROP FOREIGN KEY directus_flows_user_created_foreign');
        $this->addSql('ALTER TABLE directus_folders DROP FOREIGN KEY directus_folders_parent_foreign');
        $this->addSql('ALTER TABLE directus_notifications DROP FOREIGN KEY directus_notifications_recipient_foreign');
        $this->addSql('ALTER TABLE directus_notifications DROP FOREIGN KEY directus_notifications_sender_foreign');
        $this->addSql('ALTER TABLE directus_operations DROP FOREIGN KEY directus_operations_flow_foreign');
        $this->addSql('ALTER TABLE directus_operations DROP FOREIGN KEY directus_operations_user_created_foreign');
        $this->addSql('ALTER TABLE directus_operations DROP FOREIGN KEY directus_operations_reject_foreign');
        $this->addSql('ALTER TABLE directus_operations DROP FOREIGN KEY directus_operations_resolve_foreign');
        $this->addSql('ALTER TABLE directus_panels DROP FOREIGN KEY directus_panels_dashboard_foreign');
        $this->addSql('ALTER TABLE directus_panels DROP FOREIGN KEY directus_panels_user_created_foreign');
        $this->addSql('ALTER TABLE directus_permissions DROP FOREIGN KEY directus_permissions_role_foreign');
        $this->addSql('ALTER TABLE directus_presets DROP FOREIGN KEY directus_presets_role_foreign');
        $this->addSql('ALTER TABLE directus_presets DROP FOREIGN KEY directus_presets_user_foreign');
        $this->addSql('ALTER TABLE directus_revisions DROP FOREIGN KEY directus_revisions_activity_foreign');
        $this->addSql('ALTER TABLE directus_revisions DROP FOREIGN KEY directus_revisions_parent_foreign');
        $this->addSql('ALTER TABLE directus_sessions DROP FOREIGN KEY directus_sessions_share_foreign');
        $this->addSql('ALTER TABLE directus_sessions DROP FOREIGN KEY directus_sessions_user_foreign');
        $this->addSql('ALTER TABLE directus_settings DROP FOREIGN KEY directus_settings_public_background_foreign');
        $this->addSql('ALTER TABLE directus_settings DROP FOREIGN KEY directus_settings_public_foreground_foreign');
        $this->addSql('ALTER TABLE directus_settings DROP FOREIGN KEY directus_settings_project_logo_foreign');
        $this->addSql('ALTER TABLE directus_settings DROP FOREIGN KEY directus_settings_storage_default_folder_foreign');
        $this->addSql('ALTER TABLE directus_shares DROP FOREIGN KEY directus_shares_collection_foreign');
        $this->addSql('ALTER TABLE directus_shares DROP FOREIGN KEY directus_shares_role_foreign');
        $this->addSql('ALTER TABLE directus_shares DROP FOREIGN KEY directus_shares_user_created_foreign');
        $this->addSql('ALTER TABLE directus_users DROP FOREIGN KEY directus_users_role_foreign');
        $this->addSql('DROP TABLE directus_activity');
        $this->addSql('DROP TABLE directus_collections');
        $this->addSql('DROP TABLE directus_dashboards');
        $this->addSql('DROP TABLE directus_fields');
        $this->addSql('DROP TABLE directus_files');
        $this->addSql('DROP TABLE directus_flows');
        $this->addSql('DROP TABLE directus_folders');
        $this->addSql('DROP TABLE directus_migrations');
        $this->addSql('DROP TABLE directus_notifications');
        $this->addSql('DROP TABLE directus_operations');
        $this->addSql('DROP TABLE directus_panels');
        $this->addSql('DROP TABLE directus_permissions');
        $this->addSql('DROP TABLE directus_presets');
        $this->addSql('DROP TABLE directus_relations');
        $this->addSql('DROP TABLE directus_revisions');
        $this->addSql('DROP TABLE directus_roles');
        $this->addSql('DROP TABLE directus_sessions');
        $this->addSql('DROP TABLE directus_settings');
        $this->addSql('DROP TABLE directus_shares');
        $this->addSql('DROP TABLE directus_users');
        $this->addSql('DROP TABLE directus_webhooks');
        $this->addSql('ALTER TABLE news ADD images VARCHAR(255) DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE directus_activity (id INT UNSIGNED AUTO_INCREMENT NOT NULL, action VARCHAR(45) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ip VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, user_agent VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, item VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, comment TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, origin VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_activity_collection_foreign (collection), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_collections (collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, `group` VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, display_template VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, hidden TINYINT(1) DEFAULT 0 NOT NULL, singleton TINYINT(1) DEFAULT 0 NOT NULL, translations JSON DEFAULT NULL, archive_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, archive_app_filter TINYINT(1) DEFAULT 1 NOT NULL, archive_value VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, unarchive_value VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, sort_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, accountability VARCHAR(255) CHARACTER SET utf8 DEFAULT \'all\' COLLATE `utf8_general_ci`, color VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, item_duplication_fields JSON DEFAULT NULL, sort INT DEFAULT NULL, collapse VARCHAR(255) CHARACTER SET utf8 DEFAULT \'open\' NOT NULL COLLATE `utf8_general_ci`, INDEX directus_collections_group_foreign (`group`), PRIMARY KEY(collection)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_dashboards (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user_created CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT \'dashboard\' NOT NULL COLLATE `utf8_general_ci`, note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, color VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_dashboards_user_created_foreign (user_created), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_fields (id INT UNSIGNED AUTO_INCREMENT NOT NULL, collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, field VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, special VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, interface VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, options JSON DEFAULT NULL, display VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, display_options JSON DEFAULT NULL, readonly TINYINT(1) DEFAULT 0 NOT NULL, hidden TINYINT(1) DEFAULT 0 NOT NULL, sort INT UNSIGNED DEFAULT NULL, width VARCHAR(30) CHARACTER SET utf8 DEFAULT \'full\' COLLATE `utf8_general_ci`, translations JSON DEFAULT NULL, note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, conditions JSON DEFAULT NULL, required TINYINT(1) DEFAULT 0, `group` VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, validation JSON DEFAULT NULL, validation_message TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_fields_collection_foreign (collection), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_files (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, folder CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, uploaded_by CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, modified_by CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, storage VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, filename_disk VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, filename_download VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, title VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, uploaded_on DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, modified_on DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, charset VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, filesize BIGINT DEFAULT NULL, width INT UNSIGNED DEFAULT NULL, height INT UNSIGNED DEFAULT NULL, duration INT UNSIGNED DEFAULT NULL, embed VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, description TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, location TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, tags TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, metadata JSON DEFAULT NULL, INDEX directus_files_modified_by_foreign (modified_by), INDEX directus_files_uploaded_by_foreign (uploaded_by), INDEX directus_files_folder_foreign (folder), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_flows (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user_created CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, color VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, description TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, status VARCHAR(255) CHARACTER SET utf8 DEFAULT \'active\' NOT NULL COLLATE `utf8_general_ci`, `trigger` VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, accountability VARCHAR(255) CHARACTER SET utf8 DEFAULT \'all\' COLLATE `utf8_general_ci`, options JSON DEFAULT NULL, operation CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX directus_flows_user_created_foreign (user_created), UNIQUE INDEX directus_flows_operation_unique (operation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_folders (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, parent CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, INDEX directus_folders_parent_foreign (parent), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_migrations (version VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_notifications (id INT UNSIGNED AUTO_INCREMENT NOT NULL, recipient CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, sender CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, status VARCHAR(255) CHARACTER SET utf8 DEFAULT \'inbox\' COLLATE `utf8_general_ci`, subject VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, message TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, collection VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, item VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_notifications_sender_foreign (sender), INDEX directus_notifications_recipient_foreign (recipient), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_operations (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, resolve CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, reject CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, flow CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user_created CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, `key` VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, type VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, position_x INT NOT NULL, position_y INT NOT NULL, options JSON DEFAULT NULL, date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX directus_operations_reject_unique (reject), INDEX directus_operations_user_created_foreign (user_created), UNIQUE INDEX directus_operations_resolve_unique (resolve), INDEX directus_operations_flow_foreign (flow), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_panels (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, dashboard CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user_created CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, color VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, show_header TINYINT(1) DEFAULT 0 NOT NULL, note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, type VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, position_x INT NOT NULL, position_y INT NOT NULL, width INT NOT NULL, height INT NOT NULL, options JSON DEFAULT NULL, date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX directus_panels_dashboard_foreign (dashboard), INDEX directus_panels_user_created_foreign (user_created), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_permissions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, role CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, action VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, permissions JSON DEFAULT NULL, validation JSON DEFAULT NULL, presets JSON DEFAULT NULL, fields TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_permissions_role_foreign (role), INDEX directus_permissions_collection_foreign (collection), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_presets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, role CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, bookmark VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, collection VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, search VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, layout VARCHAR(100) CHARACTER SET utf8 DEFAULT \'tabular\' COLLATE `utf8_general_ci`, layout_query JSON DEFAULT NULL, layout_options JSON DEFAULT NULL, refresh_interval INT DEFAULT NULL, filter JSON DEFAULT NULL, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT \'bookmark_outline\' NOT NULL COLLATE `utf8_general_ci`, color VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_presets_collection_foreign (collection), INDEX directus_presets_role_foreign (role), INDEX directus_presets_user_foreign (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_relations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, many_collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, many_field VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, one_collection VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, one_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, one_collection_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, one_allowed_collections TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, junction_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, sort_field VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, one_deselect_action VARCHAR(255) CHARACTER SET utf8 DEFAULT \'nullify\' NOT NULL COLLATE `utf8_general_ci`, INDEX directus_relations_many_collection_foreign (many_collection), INDEX directus_relations_one_collection_foreign (one_collection), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_revisions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, activity INT UNSIGNED NOT NULL, parent INT UNSIGNED DEFAULT NULL, collection VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, item VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, data JSON DEFAULT NULL, delta JSON DEFAULT NULL, INDEX directus_revisions_parent_foreign (parent), INDEX directus_revisions_collection_foreign (collection), INDEX directus_revisions_activity_foreign (activity), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_roles (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, name VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, icon VARCHAR(30) CHARACTER SET utf8 DEFAULT \'supervised_user_circle\' NOT NULL COLLATE `utf8_general_ci`, description TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, ip_access TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, enforce_tfa TINYINT(1) DEFAULT 0 NOT NULL, admin_access TINYINT(1) DEFAULT 0 NOT NULL, app_access TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_sessions (token VARCHAR(64) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, user CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, share CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, expires DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, ip VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, user_agent VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, origin VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, INDEX directus_sessions_share_foreign (share), INDEX directus_sessions_user_foreign (user), PRIMARY KEY(token)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_settings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, project_logo CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, public_foreground CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, public_background CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, storage_default_folder CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, project_name VARCHAR(100) CHARACTER SET utf8 DEFAULT \'Directus\' NOT NULL COLLATE `utf8_general_ci`, project_url VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, project_color VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, public_note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, auth_login_attempts INT UNSIGNED DEFAULT 25, auth_password_policy VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, storage_asset_transform VARCHAR(7) CHARACTER SET utf8 DEFAULT \'all\' COLLATE `utf8_general_ci`, storage_asset_presets JSON DEFAULT NULL, custom_css TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, basemaps JSON DEFAULT NULL, mapbox_key VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, module_bar JSON DEFAULT NULL, project_descriptor VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, translation_strings JSON DEFAULT NULL, default_language VARCHAR(255) CHARACTER SET utf8 DEFAULT \'en-US\' NOT NULL COLLATE `utf8_general_ci`, custom_aspect_ratios JSON DEFAULT NULL, INDEX directus_settings_public_background_foreign (public_background), INDEX directus_settings_project_logo_foreign (project_logo), INDEX directus_settings_storage_default_folder_foreign (storage_default_folder), INDEX directus_settings_public_foreground_foreign (public_foreground), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_shares (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, collection VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, role CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, user_created CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, item VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, password VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, date_created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, date_start DATETIME DEFAULT NULL, date_end DATETIME DEFAULT NULL, times_used INT DEFAULT 0, max_uses INT DEFAULT NULL, INDEX directus_shares_role_foreign (role), INDEX directus_shares_collection_foreign (collection), INDEX directus_shares_user_created_foreign (user_created), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_users (id CHAR(36) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, role CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, first_name VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, last_name VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, email VARCHAR(128) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, password VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, location VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, title VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, description TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, tags JSON DEFAULT NULL, avatar CHAR(36) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, language VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, theme VARCHAR(20) CHARACTER SET utf8 DEFAULT \'auto\' COLLATE `utf8_general_ci`, tfa_secret VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, status VARCHAR(16) CHARACTER SET utf8 DEFAULT \'active\' NOT NULL COLLATE `utf8_general_ci`, token VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, last_access DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, last_page VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, provider VARCHAR(128) CHARACTER SET utf8 DEFAULT \'default\' NOT NULL COLLATE `utf8_general_ci`, external_identifier VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, auth_data JSON DEFAULT NULL, email_notifications TINYINT(1) DEFAULT 1, UNIQUE INDEX directus_users_email_unique (email), INDEX directus_users_role_foreign (role), UNIQUE INDEX directus_users_external_identifier_unique (external_identifier), UNIQUE INDEX directus_users_token_unique (token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE directus_webhooks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, method VARCHAR(10) CHARACTER SET utf8 DEFAULT \'POST\' NOT NULL COLLATE `utf8_general_ci`, url VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, status VARCHAR(10) CHARACTER SET utf8 DEFAULT \'active\' NOT NULL COLLATE `utf8_general_ci`, data TINYINT(1) DEFAULT 1 NOT NULL, actions VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, collections VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, headers JSON DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE directus_collections ADD CONSTRAINT directus_collections_group_foreign FOREIGN KEY (`group`) REFERENCES directus_collections (collection)');
        $this->addSql('ALTER TABLE directus_dashboards ADD CONSTRAINT directus_dashboards_user_created_foreign FOREIGN KEY (user_created) REFERENCES directus_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_files ADD CONSTRAINT directus_files_modified_by_foreign FOREIGN KEY (modified_by) REFERENCES directus_users (id)');
        $this->addSql('ALTER TABLE directus_files ADD CONSTRAINT directus_files_uploaded_by_foreign FOREIGN KEY (uploaded_by) REFERENCES directus_users (id)');
        $this->addSql('ALTER TABLE directus_files ADD CONSTRAINT directus_files_folder_foreign FOREIGN KEY (folder) REFERENCES directus_folders (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_flows ADD CONSTRAINT directus_flows_user_created_foreign FOREIGN KEY (user_created) REFERENCES directus_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_folders ADD CONSTRAINT directus_folders_parent_foreign FOREIGN KEY (parent) REFERENCES directus_folders (id)');
        $this->addSql('ALTER TABLE directus_notifications ADD CONSTRAINT directus_notifications_recipient_foreign FOREIGN KEY (recipient) REFERENCES directus_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_notifications ADD CONSTRAINT directus_notifications_sender_foreign FOREIGN KEY (sender) REFERENCES directus_users (id)');
        $this->addSql('ALTER TABLE directus_operations ADD CONSTRAINT directus_operations_flow_foreign FOREIGN KEY (flow) REFERENCES directus_flows (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_operations ADD CONSTRAINT directus_operations_user_created_foreign FOREIGN KEY (user_created) REFERENCES directus_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_operations ADD CONSTRAINT directus_operations_reject_foreign FOREIGN KEY (reject) REFERENCES directus_operations (id)');
        $this->addSql('ALTER TABLE directus_operations ADD CONSTRAINT directus_operations_resolve_foreign FOREIGN KEY (resolve) REFERENCES directus_operations (id)');
        $this->addSql('ALTER TABLE directus_panels ADD CONSTRAINT directus_panels_dashboard_foreign FOREIGN KEY (dashboard) REFERENCES directus_dashboards (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_panels ADD CONSTRAINT directus_panels_user_created_foreign FOREIGN KEY (user_created) REFERENCES directus_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_permissions ADD CONSTRAINT directus_permissions_role_foreign FOREIGN KEY (role) REFERENCES directus_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_presets ADD CONSTRAINT directus_presets_role_foreign FOREIGN KEY (role) REFERENCES directus_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_presets ADD CONSTRAINT directus_presets_user_foreign FOREIGN KEY (user) REFERENCES directus_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_revisions ADD CONSTRAINT directus_revisions_activity_foreign FOREIGN KEY (activity) REFERENCES directus_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_revisions ADD CONSTRAINT directus_revisions_parent_foreign FOREIGN KEY (parent) REFERENCES directus_revisions (id)');
        $this->addSql('ALTER TABLE directus_sessions ADD CONSTRAINT directus_sessions_share_foreign FOREIGN KEY (share) REFERENCES directus_shares (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_sessions ADD CONSTRAINT directus_sessions_user_foreign FOREIGN KEY (user) REFERENCES directus_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_settings ADD CONSTRAINT directus_settings_public_background_foreign FOREIGN KEY (public_background) REFERENCES directus_files (id)');
        $this->addSql('ALTER TABLE directus_settings ADD CONSTRAINT directus_settings_public_foreground_foreign FOREIGN KEY (public_foreground) REFERENCES directus_files (id)');
        $this->addSql('ALTER TABLE directus_settings ADD CONSTRAINT directus_settings_project_logo_foreign FOREIGN KEY (project_logo) REFERENCES directus_files (id)');
        $this->addSql('ALTER TABLE directus_settings ADD CONSTRAINT directus_settings_storage_default_folder_foreign FOREIGN KEY (storage_default_folder) REFERENCES directus_folders (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_shares ADD CONSTRAINT directus_shares_collection_foreign FOREIGN KEY (collection) REFERENCES directus_collections (collection) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_shares ADD CONSTRAINT directus_shares_role_foreign FOREIGN KEY (role) REFERENCES directus_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE directus_shares ADD CONSTRAINT directus_shares_user_created_foreign FOREIGN KEY (user_created) REFERENCES directus_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE directus_users ADD CONSTRAINT directus_users_role_foreign FOREIGN KEY (role) REFERENCES directus_roles (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE news DROP images, CHANGE title title TEXT NOT NULL, CHANGE description description TEXT NOT NULL');
    }
}
