<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84jlTsx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84jlTsx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container84jlTsx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container84jlTsx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container84jlTsx\App_KernelDevDebugContainer([
    'container.build_hash' => '84jlTsx',
    'container.build_id' => '79e677d1',
    'container.build_time' => 1672750975,
], __DIR__.\DIRECTORY_SEPARATOR.'Container84jlTsx');
