<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExEvlu8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExEvlu8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExEvlu8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExEvlu8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExEvlu8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ExEvlu8',
    'container.build_id' => '1b0b21e6',
    'container.build_time' => 1672605326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExEvlu8');
