<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKIXUsux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKIXUsux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKIXUsux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKIXUsux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKIXUsux\App_KernelDevDebugContainer([
    'container.build_hash' => 'KIXUsux',
    'container.build_id' => '54c0c7b8',
    'container.build_time' => 1672325588,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKIXUsux');
